Bearer/bearer

packages/cli/package.json
packages/cli/src/commands/login.ts
packages/cli/src/commands/setup/auth.ts
packages/cli/src/utils/constants.ts

support login redirection
- @bearer/cli
- link and run bearer login

fix(cli): handle redirections from dev portal

---

.github/main.workflow
package.json
packages/express/src/index.test.ts
packages/express/tsconfig.json

build: re-try github actions

---

packages/cli/src/commands/setup/auth.ts

close #656 
- @bearer/cli
[![asciicast](https://asciinema.org/a/jDP2EugmpQkdjDhB9I4n1smZ4.svg)](https://asciinema.org/a/jDP2EugmpQkdjDhB9I4n1smZ4)
- link into an integratoin without required information
- run `yarn bearer setup:auth`
- link into an integratoin with required information
- run `yarn bearer setup:auth`

feat(cli): add hint and provider information to prompt

---

packages/cli/jest.config.js
packages/cli/package.json
packages/cli/src/commands/new.ts
packages/cli/src/tasks/init-views.ts
packages/cli/src/utils/locator.ts
packages/cli/test/commands/__snapshots__/new.test.ts.snap
packages/cli/test/commands/new.test.ts
packages/cli/test/helpers/setup.ts
packages/cli/test/helpers/utils.ts
yarn.lock

- add a template options to the `bearer new` command
- @bearer/cli
[![asciicast](https://asciinema.org/a/pqvVt4NC5noHtPG5ANxPxTzyo.svg)](https://asciinema.org/a/pqvVt4NC5noHtPG5ANxPxTzyo)

feat(cli): add template option

---

packages/cli/test/utils/__snapshots__/generator.test.ts.snap
packages/openapi-generator/__tests__/__snapshots__/generator.test.ts.snap
packages/openapi-generator/src/openapi-template.ts

Update OpenAPI Spec to include `Security` component.
https://swagger.io/docs/specification/authentication/
- @bearer/openapi-generator
**Before**
**After**

fix: update OpenAPI generated files to include Security

---

packages/functions/src/declaration.ts

Updates `TOAuth1Context` to match the expected output 

feat(functions): update TOAuth1Context

---

packages/cli/src/commands/push.ts

Checks we've got an integration from Developer Portal query
@bearer/cli
**Before**
**After**

Check integration is returned from DP query and raise if not

---

packages/functions/src/declaration.ts

Add `idToken` to OAuth2 Context

fix: add idToken to OAuth2 Context

---

packages/cli/src/commands/push.ts

Add more information to "Integration Not Found" error message
@bearer/cli
**Before**
```
✖ Transfer bundle
→ Integration not found please make sure you have correctly linked your integrati
…
Error: Integration not found please make sure you have correctly linked your integration
at Push.getSignedUrl (~/Bearer/trello/node_modules/@bearer/cli/lib/commands/push.js:94:28)
```
**After**
```
✖ Transfer bundle
→ Integration not found please make sure you have correctly linked your integrati
…
Error: Integration not found. Please make sure you have correctly linked your integration and visit https://app.staging.bearer.sh/integrations/d030fx to confirm you have access to abc123 integration.
at Push.getSignedUrl (~/Bearer/trello/node_modules/@bearer/cli/lib/commands/push.js:94:28)
```

fix: improve integration not found error message

---

packages/x-ray/__test__/__snapshots__/http-overrides.test.ts.snap
packages/x-ray/__test__/http-overrides.test.ts
packages/x-ray/src/http-overrides.ts

- Add separate logs for billing - if we log a simpler payload for billing then we reduce the risk of truncation causing a request not to be counted
- Fix max body code - limit bodies to 30kb and fix logic for truncating chunks
- @bearer/x-ray

Improve logging part 2

---

packages/functions/src/declaration.ts
packages/functions/src/functions/utils.ts

Allow statusCode to be passed from the Function

chore: pass statusCode

---

packages/node/src/client.test.ts
packages/node/src/client.ts

Update link to developer api keys
- @bearer/node

fix(node): direct link to developer keys

---

packages/cli/package.json

Provide command to update to latest if new version found
- @bearer/cli

chore: provide instructions to update bearer/cli

---

packages/x-ray/src/http-overrides.ts

- make aws logs filtered whatever the region is
- @bearer/x-ray

fix: host filtering done right

---

package.json

disable UI for the moment
we are focusing on server side stuff for the moment and want to keep UI in beta

chore: makle build, test and publish faster

---

Jenkinsfile

build: build only when master

---

packages/react/src/Connect.tsx

Make setupId optional for `Connect`
- @bearer/react

chore: remove setupId as a mandatory field

---

packages/js/src/lib/bearer.ts

fix typing issue introduce previously
- @bearer/js
- build packages: `yarn lerna bootstrap`

fix(js): setupId is optinal

---

packages/node/README.md

Update Node client README to match new `.auth` signature
- @bearer/node

Update Node client README to match new `.auth` behaviour

---

packages/js/src/__tests__/lib/bearer.test.ts
packages/js/src/lib/bearer.ts
packages/js/src/lib/event.ts

introduce an EventEmitter singleton because post-robot does not allow multiple listener on the same page
**NOTE**: test will be added later
- @bearer/js

fix: register authorize only once

---

packages/node/src/client.ts

Typing for proxy requests
- @bearer/node

fix(node): add generic types for requests

---

packages/functions/src/functions/fetch.ts

Export  the environment id variable, so that, xray can include it in the metrics payload

chore(function): add the environmentId field

---

packages/js/tsconfig.json
packages/react/tsconfig.json

- target a different ecmascript version so that people won't have to transform files
- @bearer/js
-  @bearer/react

feat: target es5 for frontend libraries

---

packages/functions/src/functions/fetch.ts

Adds `userCorrelationId` and `internalCorrelationId` to the environment variables. These will be used by the XRay package for logging.

feat(functions): add correlation ids to environment

---

packages/node/README.md
packages/node/src/client.test.ts
packages/node/src/client.ts

Make NodeJS Client more inline with NodeJS conventions
- @bearer/node

feat: make node client inline with node conventions

---

packages/functions/src/functions/fetch.test.ts
packages/functions/src/functions/utils.ts

add a link into the error message so that it gives more information to the api consumer

fix(functions): provide link to setup frontend api calls

---

packages/node/README.md
packages/node/src/client.test.ts
packages/node/src/client.ts

Allow setting timeout in BearerClient
@bearer/node

chore: allow timeout to be set
